### ISSUE TITLE
Linker is unable to find Conan-installed library

### ISSUE THREAD

**Issue by wouterbeek** [czoido/conan-gyp-generator#1]
Thanks for working on this Conan + Node-Gyp combination!  I have not found such support anywhere else :-(

When U use this, the `conanbuildinfo.gyp` file is created correctly, but the linker is not yet able to find Conan-installed libraries for some reason:

```sh
$ node-gyp build --verbose
[...]
g++ -shared -pthread -rdynamic -m64 -Wl,-rpath=\$ORIGIN/lib.target/ -Wl,-rpath-link=\./Release/lib.target/  -Wl,-soname=test.node -o Release/obj.target/test.node -Wl,--start-group Release/obj.target/test/lib/test.o Release/obj.target/test/lib/Test.o Release/obj.target/conan_build/nlohmann_json.so -Wl,--end-group -lnlohmann_json -Wl,-rpath,/home/wouter/triply/test/node/test-node/build/Release/
/usr/bin/ld: cannot find -lnlohmann_json
```

The shared library seems to be in the correct (rpath) place:

```sh
$ ls build/Release/obj.target/conan_build/
nlohmann_json.so
```

Is there anything obvious that I could be doing wrong here?

**Comment by czoido** [comment]
Hi @wouterbeek,
Thanks a lot, I'm glad you found it useful :)
I think the problem is in the fact that _nlohmann_json_ is a header-only library, I have updated the generator to consider that case, please, could you pull latest changes and try again to build ?

**Comment by wouterbeek** [comment]
@czoido Thanks for fixing this!  It works perfectly now.
