### ISSUE TITLE
Library/dependency name mismatch (`-lz` versus `-lzlib`)

### ISSUE THREAD

**Issue by wouterbeek** [czoido/conan-gyp-generator#3]
When I use the `zlib/1.2.11` dependency, my Node-Gyp build fails because library `-lzlib` could not be found.

When I look into the file `conanbuildinfo.txt`, the library for the `zlib` dependency is called `z`.  However, it is specified as `-lzlib` in `conanbuildinfo.gyp`.

Indeed, manually changing `-lzlib` into `-lz` inside `conanbuildinfo.gyp` fixes the Node-Gyp build.

Could it be that the library name is currently assumed to be identical to the dependency name?  If so, would it be possible to use the actual library name instead?

**Comment by czoido** [comment]
Hi @wouterbeek,
Thanks a lot for reporting. It should be fixed now after https://github.com/czoido/conan-gyp-generator/pull/4, please check if it's working correctly now.
Also, please reopen if you have further issues.

**Comment by wouterbeek** [comment]
Thanks, this is now fixed!
